# Generated by Django 3.2.11 on 2023-09-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sin_bau_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tb_1",
            old_name="naem",
            new_name="name",
        ),
    ]
