# Generated by Django 3.2.11 on 2023-09-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sin_bau_api", "0002_rename_naem_tb_1_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tb_1",
            name="candy_or_cookie",
            field=models.CharField(choices=[("0", "糖果"), ("1", "餅乾")], default="0", max_length=1),
        ),
    ]
