# Generated by Django 3.2.11 on 2023-09-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sin_bau_api", "0005_alter_tb_1_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tb_1",
            options={"verbose_name": "用戶資料庫", "verbose_name_plural": "用戶資料庫"},
        ),
    ]
