# Generated by Django 3.2.11 on 2023-09-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naem', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
