# Generated by Django 3.2.11 on 2023-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tb_1_candy_or_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_1',
            name='name',
            field=models.CharField(choices=[('0', 'Dio'), ('1', 'Admin'), ('2', '陳佳宏')], max_length=64),
        ),
    ]
