# Generated by Django 3.2.11 on 2023-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_tb_1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_1',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
