# Generated by Django 3.2.11 on 2023-09-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20230928_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_1',
            options={'ordering': ['-_time'], 'verbose_name': '用戶資料庫', 'verbose_name_plural': '用戶資料庫'},
        ),
    ]
