# Generated by Django 3.2.11 on 2023-12-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_article_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='p', max_length=1, null=True, verbose_name='Status (*)'),
        ),
    ]
